//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAppRessourcen
{
    using System;
    
    public enum Status : short
    {
        Vorerfasst = 1,
        Aktiv = 2,
        Erledigt = 3,
        Abgebrochen = 99
    }
}
